### ISSUE TITLE
input file argument is not detected

### ISSUE THREAD

**Issue by rachidbch** [deadratfink/jy-transform#36]
on v1.0.2 option that have just installed normal cli use  throws a error: 

Cli command: 
 $ ' jyt foo.yaml -t json -i 2'

error message: 
ERROR: Error: missing options property(s): ["options.src"]!

I have to specify the source argument to have it work: 
$ ' jyt -s foo.yaml -t json -i 2'

According to the doc this is not the epected behaviour.

thx and keep the good work!

**Comment by deadratfink** [comment]
Hi rachidbch,

thx for using this module. Indeed, you have to use:

```
$  jyt -s foo.yaml -t json -i 2
```

The style you used above for 1.0.2 is the new one for upcoming version 2.0.0 only (not released yet). 

Please refer and check with [master branch README](https://github.com/deadratfink/jy-transform/blob/master/README.md) or [latest tag (v1.0.2) README](https://github.com/deadratfink/jy-transform/tree/v1.0.2). Sorry for confusion, the development  branch should not reflect the latest unpublished one's documentation. Yes, I should avoid this in future not to confuse others again.

Hope this hint will solve your issue, if yes then please close this issue, else please report further problems and I will try to help out. 

Best regards
Jens

**Comment by deadratfink** [comment]
I reverted the README.md on _development_ branch reflecting the state of v1.0.2.

**Comment by deadratfink** [comment]
Closed, because this does not have to be fixed on code level.

**Comment by rachidbch** [comment]
Thanks for the answer. 
Waiting for v2 then  ... :)

**Comment by deadratfink** [comment]
Hi, FYI v2 is out now...

Best regards
Jens

Von meinem iPad gesendet
