### ISSUE TITLE
Create example code starting at require

### ISSUE THREAD

**Issue by Industrial** [deadratfink/jy-transform#43]
Hi.

I would like to request a change in the documentation:

Most NPM module start out with

```
Installation:
    npm i --save<mypackage>
```

And then

```
Usage:
    const x = require('<mypackage');

    x(() => {
      // Do practical stuff here

      console.log('Look, benefit!');
    });
```

https://github.com/deadratfink/jy-transform#api-usage does not tell me how to start using the API. It only lists all the possible permutations in the configuration. It's complete but not practical.

**Comment by deadratfink** [comment]
Hi, yes good point! At the moment I am thinking about overhauling the whole lib to make it more modern (e.g. es6, new test framework like Jest and so forth). Then I would also consider to rewrite the documentation here and there and also making a better structure.

I leave this Issue open that it won't be forget ;-)

Thx for the feedback and let me know whenever you need support.
